spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/habit_tracker
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
