spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/habit_tracker
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    generate-ddl: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE